# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" #Substitua por "composer", "maven", "pip", etc., dependendo do gerenciador de pacotes do seu projeto
    directory: "./Portfolio" #Caminho para o diretório onde está o arquivo do gerenciador de pacotes (package.json, composer.json, etc.)
    schedule:
      interval: "weekly" #Intervalo de verificação das atualizações (diário, semanal, mensal)
